# permissions for end users to view awsbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forge-provider-aws
    app.kubernetes.io/managed-by: kustomize
  name: awsbuild-viewer-role
rules:
- apiGroups:
  - infrastructure.forge.build
  resources:
  - awsbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.forge.build
  resources:
  - awsbuilds/status
  verbs:
  - get
